#include <Date.au3>
#include <FileConstants.au3>
#include <MsgBoxConstants.au3>

$sFile1=@ScriptDir & "\buyprice.txt"
$sFile2=@ScriptDir & "\sellprice.txt"
$buy=@ScriptDir & "\buy.exe"
$sell=@ScriptDir & "\sell.exe"

;Read Price File generated by Amibroker
Local $buyprice = @ScriptDir & "\buyprice.txt"
Local $hFileOpen = FileOpen($buyprice, $FO_APPEND + $FO_CREATEPATH)
FileSetPos($hFileOpen, 0, $FILE_BEGIN)
Local $buyprice = FileReadLine ($hFileOpen,1)
FileClose($hFileOpen)


;Read Price File generated by Amibroker
Local $buyprice = @ScriptDir & "\sellprice.txt"
Local $hFileOpen = FileOpen($buyprice, $FO_APPEND + $FO_CREATEPATH)
FileSetPos($hFileOpen, 0, $FILE_BEGIN)
Local $sellprice = FileReadLine ($hFileOpen,1)
FileClose($hFileOpen)


$FileTime1 = FileGetTime($sFile1, 0, 1)
$FileTime2 = FileGetTime($sFile2, 0, 1)

If $FileTime1>$FileTime2 Then
	msgbox(0,'','BuyPrice is ' & $buyprice)
else
	if $FileTime2>$FileTime1 Then
	msgbox(0,'','SellPrice is ' & $sellprice)
endif
endif