#include <FileConstants.au3>
#include <MsgBoxConstants.au3>

;Read Price File generated by Amibroker/excel
Local $buyprice = @ScriptDir & "\buyprice.txt"
Local $hFileOpen = FileOpen($buyprice, $FO_APPEND + $FO_CREATEPATH)
FileSetPos($hFileOpen, 0, $FILE_BEGIN)
Local $buyprice = FileReadLine ($hFileOpen,1)
FileClose($hFileOpen)

;Read Ini File created by Config
$sFilePath = @ScriptDir & "\config.ini"
Local $takeprofit = IniRead($sFilePath, "Value", "TP", "Default Value")
Local $stoploss = IniRead($sFilePath, "Value", "SL", "Default Value")
Local $qty = IniRead($sFilePath, "Value", "Qty", "Default Value")
Local $Inst = IniRead($sFilePath, "Value", "Inst", "Default Value")
Local $segment = IniRead($sFilePath, "Value", "Segment", "Default Value")
Local $symbol = IniRead($sFilePath, "Value", "Symbol", "Default Value")
Local $option = IniRead($sFilePath, "Value", "Option", "Default Value")
Local $expiry = IniRead($sFilePath, "Value", "Expiry", "Default Value")
Local $strike = IniRead($sFilePath, "Value", "Strike", "Default Value")
Local $ordertype = IniRead($sFilePath, "Value", "OrderType", "Default Value")

;Automation Code for Selecting

if $ordertype == "Market Order" Then
   WinActivate("Welcome")
   Send("{DOWN}")
   Send("{F1}")
   Sleep(1000)
   WinActivate("Buy Order")
   ControlCommand("Buy Order","",2602,"SelectString",$segment)  ; Select Exchange
   ControlCommand("Buy Order","",2632,"SelectString","MARKET")  ; Select Market
   ControlCommand("Buy Order","",2656,"SelectString",$Inst) ; Select instrument
   ControlCommand("Buy Order","",2657,"SelectString",$symbol) ;Select symbol
   ControlCommand("Buy Order","",2631,"SelectString",$option) ;Select option type ce/pe
   ControlCommand("Buy Order","",2658,"SelectString",$strike) ;Select option strike
   ControlCommand("Buy Order","",2636,"SelectString",$expiry) ;Select option expiry
   ControlSetText("Buy Order","",2640,$qty) ; Qty
   Send("{Enter}")


ElseIf $ordertype == "Bracket Order" Then
   WinActivate("Welcome")
   Send("{DOWN}")
   Send("+{F3}")
   Sleep(1000)
   WinActivate("Buy Bracket")
   ControlCommand("Buy Bracket","",2602,"SelectString",$segment)  ; Select Exchange
   ControlCommand("Buy Bracket","",2656,"SelectString",$Inst) ; Select instrument
   ControlCommand("Buy Bracket","",2657,"SelectString",$symbol) ;Select symbol
   ControlCommand("Buy Bracket","",2631,"SelectString",$option) ;Select option type ce/pe
   ControlCommand("Buy Bracket","",2658,"SelectString",$strike) ;Select option strike
   ControlCommand("Buy Bracket","",2636,"SelectString",$expiry) ;Select option expiry
   ControlSetText("Buy Bracket","",2640,$qty) ; Qty
   ControlSetText("Buy Bracket","",2639,$buyprice) ;Limit Price
   ControlSetText("Buy Bracket","",1934,$takeprofit) ;Take Profit
   ControlSetText("Buy Bracket","",1936,$stoploss) ;Stop Loss
   ControlCommand("Buy Bracket","",1413,"Check") ; Absolute Check
   ControlCommand("Buy Bracket","",1410,"Check") ; Absolute Check
   Send("{Enter}")

ElseIf $ordertype == "Limit Order" Then
	WinActivate("Welcome")
	Send("{DOWN}")
	Send("{F1}")
	Sleep(1000)
	WinActivate("Buy Order")
	ControlCommand("Buy Order","",2602,"SelectString",$segment)  ; Select Exchange
	ControlCommand("Buy Order","",2656,"SelectString",$Inst) ; Select instrument
	ControlCommand("Buy Order","",2657,"SelectString",$symbol) ;Select symbol
	ControlCommand("Buy Order","",2631,"SelectString",$option) ;Select option type ce/pe
	ControlCommand("Buy Order","",2658,"SelectString",$strike) ;Select option strike
	ControlCommand("Buy Order","",2636,"SelectString",$expiry) ;Select option expiry
	ControlSetText("Buy Order","",2640,$qty) ; Qty
	ControlSetText("Buy Order","",2639,$buyprice) ;Limit Price
	Send("{Enter}")


Else
	if $ordertype == "Cover Order" Then
	WinActivate("Welcome")
	Send("{DOWN}")
	Send("+{F1}")
	Sleep(1000)
	WinActivate("Buy Cover")
	ControlCommand("Buy Cover","",2602,"SelectString",$segment)  ; Select Exchange
	ControlCommand("Buy Cover","",2656,"SelectString",$Inst) ; Select instrument
	ControlCommand("Buy Cover","",2657,"SelectString",$symbol) ;Select symbol
	ControlCommand("Buy Cover","",2631,"SelectString",$option) ;Select option type ce/pe
	ControlCommand("Buy Cover","",2658,"SelectString",$strike) ;Select option strike
	ControlCommand("Buy Cover","",2636,"SelectString",$expiry) ;Select option expiry
	ControlSetText("Buy Cover","",2640,$qty) ; Qty
	ControlSetText("Buy Cover","",1968,$buyprice) ;Limit Price
	ControlSetText("Buy Cover","",2802,$stoploss) ;Stop Loss
	Send("{Enter}")

  EndIf
EndIf