#include <FileConstants.au3>
#include <MsgBoxConstants.au3>

;Read Price File generated by Amibroker/excel
Local $Sellprice = (@ScriptDir & "\sellprice.txt")
Local $hFileOpen = FileOpen($Sellprice, $FO_APPEND + $FO_CREATEPATH)
FileSetPos($hFileOpen, 0, $FILE_BEGIN)
Local $Sellprice = FileReadLine ($hFileOpen,1)
FileClose($hFileOpen)

;Read Ini File created by Config
$sFilePath = @ScriptDir & "\config.ini"
Local $takeprofit = IniRead($sFilePath, "Value", "TP", "Default Value")
Local $stoploss = IniRead($sFilePath, "Value", "SL", "Default Value")
Local $qty = IniRead($sFilePath, "Value", "Qty", "Default Value")
Local $Inst = IniRead($sFilePath, "Value", "Inst", "Default Value")
Local $segment = IniRead($sFilePath, "Value", "Segment", "Default Value")
Local $symbol = IniRead($sFilePath, "Value", "Symbol", "Default Value")
Local $option = IniRead($sFilePath, "Value", "Option", "Default Value")
Local $expiry = IniRead($sFilePath, "Value", "Expiry", "Default Value")
Local $strike = IniRead($sFilePath, "Value", "Strike", "Default Value")
Local $ordertype = IniRead($sFilePath, "Value", "OrderType", "Default Value")

;Automation Code for Selecting

if $ordertype == "Market Order" Then
   WinActivate("Welcome")
   Send("{DOWN}")
   Send("{F2}")
   Sleep(1000)
   WinActivate("Sell Order")
   ControlCommand("Sell Order","",2602,"SelectString",$segment)  ; Select Exchange
   ControlCommand("Sell Order","",2632,"SelectString","MARKET")  ; Select Market
   ControlCommand("Sell Order","",2656,"SelectString",$Inst) ; Select instrument
   ControlCommand("Sell Order","",2657,"SelectString",$symbol) ;Select symbol
   ControlCommand("Sell Order","",2631,"SelectString",$option) ;Select option type ce/pe
   ControlCommand("Sell Order","",2658,"SelectString",$strike) ;Select option strike
   ControlCommand("Sell Order","",2636,"SelectString",$expiry) ;Select option expiry
   ControlSetText("Sell Order","",2640,$qty) ; Qty
   Send("{Enter}")


ElseIf $ordertype == "Bracket Order" Then
   WinActivate("Welcome")
   Send("{DOWN}")
   Send("+{F4}")
   Sleep(1000)
   WinActivate("Sell Bracket")
   ControlCommand("Sell Bracket","",2602,"SelectString",$segment)  ; Select Exchange
   ControlCommand("Sell Bracket","",2656,"SelectString",$Inst) ; Select instrument
   ControlCommand("Sell Bracket","",2657,"SelectString",$symbol) ;Select symbol
   ControlCommand("Sell Bracket","",2631,"SelectString",$option) ;Select option type ce/pe
   ControlCommand("Sell Bracket","",2658,"SelectString",$strike) ;Select option strike
   ControlCommand("Sell Bracket","",2636,"SelectString",$expiry) ;Select option expiry
   ControlSetText("Sell Bracket","",2640,$qty) ; Qty
   ControlSetText("Sell Bracket","",2639,$Sellprice) ;Limit Price
   ControlSetText("Sell Bracket","",1934,$takeprofit) ;Take Profit
   ControlSetText("Sell Bracket","",1936,$stoploss) ;Stop Loss
   ControlCommand("Sell Bracket","",1413,"Check") ; Absolute Check
   ControlCommand("Sell Bracket","",1410,"Check") ; Absolute Check
   Send("{Enter}")

ElseIf $ordertype == "Limit Order" Then
	WinActivate("Welcome")
	Send("{DOWN}")
	Send("{F2}")
	Sleep(1000)
	WinActivate("Sell Order")
	ControlCommand("Sell Order","",2602,"SelectString",$segment)  ; Select Exchange
	ControlCommand("Sell Order","",2656,"SelectString",$Inst) ; Select instrument
	ControlCommand("Sell Order","",2657,"SelectString",$symbol) ;Select symbol
	ControlCommand("Sell Order","",2631,"SelectString",$option) ;Select option type ce/pe
	ControlCommand("Sell Order","",2658,"SelectString",$strike) ;Select option strike
	ControlCommand("Sell Order","",2636,"SelectString",$expiry) ;Select option expiry
	ControlSetText("Sell Order","",2640,$qty) ; Qty
	ControlSetText("Sell Order","",2639,$Sellprice) ;Limit Price
	Send("{Enter}")


Else
	if $ordertype == "Cover Order" Then
	WinActivate("Welcome")
	Send("{DOWN}")
	Send("+{F2}")
	Sleep(1000)
	WinActivate("Sell Cover")
	ControlCommand("Sell Cover","",2602,"SelectString",$segment)  ; Select Exchange
	ControlCommand("Sell Cover","",2656,"SelectString",$Inst) ; Select instrument
	ControlCommand("Sell Cover","",2657,"SelectString",$symbol) ;Select symbol
	ControlCommand("Sell Cover","",2631,"SelectString",$option) ;Select option type ce/pe
	ControlCommand("Sell Cover","",2658,"SelectString",$strike) ;Select option strike
	ControlCommand("Sell Cover","",2636,"SelectString",$expiry) ;Select option expiry
	ControlSetText("Sell Cover","",2640,$qty) ; Qty
	ControlSetText("Sell Cover","",1968,$Sellprice) ;Limit Price
	ControlSetText("Sell Cover","",2802,$stoploss) ;Stop Loss
	Send("{Enter}")

  EndIf
EndIf